In [2]:
import numpy as np

In [3]:
img0 = [[0,1,2],
        [3,4,5],
        [6,7,8]]

In [4]:
img0arr = np.array(img0)

In [5]:
print(img0,img0arr)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]] [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
print(type(img0))

<class 'list'>


In [7]:
print(type(img0arr))

<class 'numpy.ndarray'>


In [8]:
print(len(img0))

3


In [9]:
print(img0arr.shape)

(3, 3)


In [10]:
print(img0*30)

[[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [11]:
print(img0+img0)

[[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [12]:
print(img0arr*30)

[[  0  30  60]
 [ 90 120 150]
 [180 210 240]]


In [13]:
print(img0arr+img0arr)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [14]:
print(img0arr*img0arr)

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [17]:
print(np.matmul(img0arr.T,img0arr))

[[45 54 63]
 [54 66 78]
 [63 78 93]]


In [16]:
print(img0arr.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [2]:
import pycifrw

ModuleNotFoundError: No module named 'pycifrw'

In [19]:
pip install PyCifRW

     |████████████████████████████████| 1.1 MB 10.7 MB/s eta 0:00:01[K     |███████████████████▎            | 645 kB 10.7 MB/s eta 0:00:01
  Created wheel for PyCifRW: filename=PyCifRW-4.4.3-cp38-cp38-linux_x86_64.whl size=165110 sha256=ba431ee43180e1ecb083b30225e17a6d2c972585654cd3e0cd347e1583447aa0
  Stored in directory: /home/idies/.cache/pip/wheels/d3/2a/90/c6700f618a0630c91b4c6d8ba6eb95fcc64369c5d94a27721b
Successfully built PyCifRW
Note: you may need to restart the kernel to use updated packages.


In [3]:
from CifFile import ReadCif
cf = ReadCif('P1-A.cif')

In [6]:
print(cf.keys())

['generated_by_bilbao_crystallographic_server']


In [11]:
d1 = {'d1':56,'d2':[7,8,9],'d3':"Hello"}

In [12]:
print(d1.values())

dict_values([56, [7, 8, 9], 'Hello'])


In [13]:
print(cf['generated_by_bilbao_crystallographic_server'])


_cell_length_a                          5.286316
_cell_length_b                          5.286316
_cell_length_c                          11.8353765
_cell_angle_alpha                       90.000000
_cell_angle_beta                        90.000000
_cell_angle_gamma                       120.000000
_symmetry_space_group_name_H-M          P1
_symmetry_Int_Tables_number             1
loop_
  _symmetry_equiv_pos_site_id
  _symmetry_equiv_pos_as_xyz
         1         'x,y,z' 
loop_
  _atom_site_label
  _atom_site_type_symbol
  _atom_site_fract_x
  _atom_site_fract_y
  _atom_site_fract_z
         Na1       Na        0.33333   0         0         
         Na1002    Na        0         0.33333   0         
         Na1003    Na        0.66667   0.66667   0         
         O1        O         0.33333   0.33333   0.1378    
         O1002     O         0.66667   0         0.1378    
         O1003     O         0         0.66667   0.1378    
         Co2       Co        0.33333   0.66667  