In [1]:
import numpy as np

In [2]:
img0 = [[0,1,2],
        [3,4,5],
        [6,7,8]]

In [3]:
img0arr = np.array(img0)

In [4]:
print(img0,img0arr)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]] [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
print(type(img0))

<class 'list'>


In [6]:
print(type(img0arr))

<class 'numpy.ndarray'>


In [7]:
print(len(img0))

3


In [8]:
print(img0arr.shape)

(3, 3)


In [9]:
print(img0*30)

[[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [10]:
print(img0+img0)

[[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [11]:
print(img0arr*30)

[[  0  30  60]
 [ 90 120 150]
 [180 210 240]]


In [12]:
print(img0arr+img0arr)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [13]:
print(img0arr*img0arr)

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [14]:
print(np.matmul(img0arr.T,img0arr))

[[45 54 63]
 [54 66 78]
 [63 78 93]]


In [15]:
print(img0arr.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [16]:
pip install PyCifRW

Note: you may need to restart the kernel to use updated packages.


In [17]:
from CifFile import ReadCif
cf = ReadCif('P1-A.cif')

In [18]:
print(cf.keys())

['vesta_phase_1']


In [19]:
d1 = {'d1':56,'d2':[7,8,9],'d3':"Hello"}

In [20]:
print(d1.values())

dict_values([56, [7, 8, 9], 'Hello'])


In [21]:
print(cf['vesta_phase_1'])


_chemical_name_common                   'New structure'
_cell_length_a                          7.123000
_cell_length_b                          9.933000
_cell_length_c                          3.100000
_cell_angle_alpha                       90.000000
_cell_angle_beta                        90.000000
_cell_angle_gamma                       90.000000
_cell_volume                            219.333542
_space_group_name_H-M_alt               'P b a m'
_space_group_IT_number                  55
loop_
  _space_group_symop_operation_xyz
         'x, y, z'           
         '-x, -y, -z'        
         '-x, -y, z'         
         'x, y, -z'          
         '-x+1/2, y+1/2, -z'           
         'x+1/2, -y+1/2, z'  
         'x+1/2, -y+1/2, -z'           
         '-x+1/2, y+1/2, z' 
loop_
  _atom_site_label
  _atom_site_occupancy
  _atom_site_fract_x
  _atom_site_fract_y
  _atom_site_fract_z
  _atom_site_adp_type
  _atom_site_U_iso_or_equiv
  _atom_site_type_symbol
         Ni     